export const products = [
  {
    id: 1,
    name: "Airpods Wireless Bluetooth Headphones",
    image: "/images/airpods.jpg",
    description:
      "Bluetooth technology lets you connect it with compauble devices wirelessly High-quality AAC audio offers immersive listeing experience Build in microphone allows you to take calls while working",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 20,
    rating: 4.5,
    numReviews: 12,
  },
  {
    id: 2,
    name: "RTX GeForce Rog Strix Gaming 4090",
    image: "/images/4090.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo laboriosam voluptates natus porro eveniet illum maxime inventore unde modi animi?",
    brand: "Rog Strix",
    category: "Electronics",
    price: 489.99,
    countInStock: 5,
    rating: 5,
    numReviews: 3,
  },
  {
    id: 3,
    name: "AMD Ryzen Threadripper",
    image: "/images/threadripper.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo laboriosam voluptates natus porro eveniet illum maxime inventore unde modi animi?",
    brand: "AMD",
    category: "Electronics",
    price: 789.99,
    countInStock: 2,
    rating: 5,
    numReviews: 8,
  },
  {
    id: 4,
    name: "Nike Jordans",
    image: "/images/jordans.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo laboriosam voluptates natus porro eveniet illum maxime inventore unde modi animi?",
    brand: "Nike",
    category: "Shoes",
    price: 120.0,
    countInStock: 0,
    rating: 5,
    numReviews: 0,
  },
  {
    id: 5,
    name: "Play Station 5",
    image: "/images/ps5.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo laboriosam voluptates natus porro eveniet illum maxime inventore unde modi animi?",
    brand: "Sony",
    category: "Electronics",
    price: 250.99,
    countInStock: 3,
    rating: 3.5,
    numReviews: 2,
  },

  {
    id: 6,
    name: "Rolex",
    image: "/images/rolex.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo laboriosam voluptates natus porro eveniet illum maxime inventore unde modi animi?",
    brand: "Rolex",
    category: "Watch",
    price: 1289.99,
    countInStock: 1,
    rating: 5,
    numReviews: 8,
  },
  {
    id: 7,
    name: "Samsung Flip",
    image: "/images/samsung.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo laboriosam voluptates natus porro eveniet illum maxime inventore unde modi animi?",
    brand: "Samsung",
    category: "Electronics",
    price: 189.99,
    countInStock: 12,
    rating: 4.5,
    numReviews: 2,
  },
];
